/**
 * Composition spec types — this is the JSON contract between the MCP tool and Remotion.
 * The MCP tool generates a CompositionSpec; Remotion reads it and renders video.
 */

export interface ClipSpec {
  order: number;
  label: string;
  /** Absolute path to the source media file (video/image/audio) */
  mediaPath?: string;
  /** Duration of this clip in seconds */
  duration: number;
  /** Trim points for source media */
  trimStart?: number;
  trimEnd?: number;
  /** Visual effect to apply */
  effect?: "none" | "ken_burns" | "slow_mo" | "speed_ramp";
  /** Text overlay on this clip */
  textOverlay?: string;
  /** Position of text overlay */
  textPosition?: "bottom-third" | "center" | "top";
  /** Voiceover audio path (generated by ElevenLabs) */
  voiceoverPath?: string;
  /** Transition to next clip */
  transition?: "cut" | "fade" | "dissolve" | "none";
  /** Whether this clip is AI-generated (for watermark/badge) */
  aiGenerated?: boolean;
}

export interface CompositionSpec {
  projectId: string;
  title: string;
  /** Output dimensions */
  width: number;
  height: number;
  fps: number;
  /** Clips in order */
  clips: ClipSpec[];
  /** Background music track path */
  musicPath?: string;
  /** Music volume (0-1) */
  musicVolume?: number;
  /** Output file path */
  outputPath: string;
}
